### ISSUE TITLE
درخواست راهنما برای راه‌اندازی و اجرای پروژه

### ISSUE THREAD

**Issue by ekm507** [SHMF1385/SmartNotebook-Server#1]
سلام!

لطفا یک راهنما برای راه‌اندازی و اجرای پروژه اضافه کنید. می‌توانید با ساختن فایل README.md این کار را انجام دهید.

اگر نوشتن این فایل برای شما سخته، می‌تونید اینجا نحوه راه‌اندازی رو توضیح بدهید تا من فایل رو برای شما بنویسم.

**Comment by shmf1385** [comment]
سلام

ممنون از پیشنهادتون

حتما اضافه می شود

**Comment by shmf1385** [comment]
انجام شد
